baseURL = "https://animalsociety.github.io/blog/"
languageCode = "en-us"
title = "Animal Society"
theme = "hugo-PaperMod"

[Params]
defaultTheme = "dark"
disableThemeToggle = true
ShowShareButtons = false